### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nesquik011** [alvarobasi/QtStereoCamProject#1]
is there .exe so i can try it ?  and what camera can I use ?  is webcam fine ?

**Comment by alvarobasi** [comment]
Hi! Sorry for the delay. Will look for it but I'd say not at the moment. Yes, any USB camera should be fine. I used C920s for this project.

**Comment by spacex22** [comment]
can it make point cloud from video ? do I need projector ?

**Comment by nesquik011** [comment]
can it make point cloud from video? do I need projector ?

**Comment by alvarobasi** [comment]
Hi! No, only a single disparity map is supported for point cloud computation. However, feel free to modify the code in order to do it sequentially for each pair of images taken from your video. It shouldn't be that hard ;)
